dbt_project_test:
  outputs:
    dev:
      account: xoa86772.us-east-1
      database: DBT_ANALYTICS
      password: '@#$%&09SFEsfe'
      role: ANALYTICS_ENGINEER
      schema: DBT_LKONDRU
      threads: 15
      type: snowflake
      user: lakshmi.kondru
      warehouse: DBT_WH
  target: dev
