dbt_project_test:
  outputs:
    dev:
      account: ${{ secrets.DBT_ACCOUNT }}
      database: ${{ secrets.DBT_DATABASE }}
      password: ${{ secrets.DBT_PASSWORD }}
      role: ${{ secrets.DBT_ROLE }}
      schema: ${{ secrets.DBT_SCHEMA }}
      threads: 15
      type: snowflake
      user: ${{ secrets.DBT_USER }}
      warehouse: ${{ secrets.DBT_WAREHOUSE }}
  target: dev
