name: Run dbt project evaluator CI check

on:
  push:
    branches:
      - featureA
  pull_request:
    branches:
      - main

jobs:
  compile:
    name: Build and Compile dbt Project
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo hosting the dbt project
        uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dbt CLI and SQLFluff
        run: |
          pip install dbt-snowflake sqlfluff
          
      - name: Configure dbt profiles
        run: |
          echo "${{ secrets.DBT_PROFILES }}" > $HOME/.dbt/profiles.yml
          
      - name: Display dbt profiles
        run: |
          cat $HOME/.dbt/profiles.yml

      - name: Get and Use dbt docker image to access dbt project
        uses: addnab/docker-run-action@v3
        with:
          image: ghcr.io/dbt-labs/dbt-snowflake:latest
          options: -v ${{ github.workspace }}:/work -e PROJECT_NAME=dbt_master
          shell: bash
        run: |
          cd /work
          ls -ltr /work
          dbt deps
          dbt build --select package:dbt_project_evaluator
