name: Run dbt project evaluator CI check

on:
  push:
    branches:
      - featureA
  pull_request:
    branches:
      - main
  workflow_dispatch:

env:
  DBT_PROJECT_NAME: DBT_Jaffle_Shop_LK
  DTB_ACCOUNT: ${{ secrets.DBT_ACCOUNT }}
  DBT_USER : ${{ secrets.DBT_USER  }}
  DBT_PASSWORD : ${{ secrets.DBT_PASSWORD  }}
  DBT_ROLE : ${{ secrets.DBT_ROLE  }}
  DBT_DATABASE : ${{ secrets.DBT_DATABASE  }}
  DBT_SCHEMA : ${{ secrets.DBT_SCHEMA  }}
  DBT_WAREHOUSE  : ${{ secrets.DBT_WAREHOUSE   }}
  DBT_NUM_THREADS: 15

jobs:
  compile:
    name: Build and Compile dbt Project
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo hosting the dbt project
        uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dbt CLI and SQLFluff
        run: |
          pip install dbt-core dbt-snowflake sqlfluff
          
      - name: Configure dbt profiles
        env:
          DBT_PROFILES: ${{ github.workspace }}/.dbt

      - name: Get dbt Docker image
        run: docker pull ghcr.io/dbt-labs/dbt-snowflake:latest

      - name: Use dbt Docker image to access dbt project
        run: |
          mkdir -p /home/runner/.dbt
          docker run -v ${{ github.workspace }}:/work -e PROJECT_NAME=dbt_master \
            ghcr.io/dbt-labs/dbt-snowflake:latest bash -c "cd /work && ls -ltr /work && dbt deps && dbt build --select package:dbt_project_evaluator"
